import '../spec.dart';
import 'context.dart';

String onboardingScreenDart(TemplateContext c) => lines([
  "import 'package:flutter/material.dart';",
  ...c.coreImports,
  '',
  ...c.l10nImports,
  '',
  '/// Shown until [OnboardingState.markAsSeen] — the gate moves on by itself.',
  'class OnboardingScreen extends ConsumerStatefulWidget {',
  '  const OnboardingScreen({super.key});',
  '',
  "  static const String path = '/onboarding';",
  '',
  '  @override',
  '  ConsumerState<OnboardingScreen> createState() => _OnboardingScreenState();',
  '}',
  '',
  'class _OnboardingScreenState extends ConsumerState<OnboardingScreen> {',
  '  final _controller = PageController();',
  '  int _page = 0;',
  '',
  '  @override',
  '  void dispose() {',
  '    _controller.dispose();',
  '    super.dispose();',
  '  }',
  '',
  '  void _finish() => ref.read(onboardingStateProvider.notifier).markAsSeen();',
  '',
  '  @override',
  '  Widget build(BuildContext context) {',
  '    final pages = [',
  "      (Icons.dashboard_customize_outlined, ${c.t('onboarding1Title')}, ${c.t('onboarding1Body')}),",
  "      (Icons.bolt_outlined, ${c.t('onboarding2Title')}, ${c.t('onboarding2Body')}),",
  "      (Icons.rocket_launch_outlined, ${c.t('onboarding3Title')}, ${c.t('onboarding3Body')}),",
  '    ];',
  '    final isLast = _page == pages.length - 1;',
  '    final colors = context.colorScheme;',
  '',
  '    return Scaffold(',
  '      body: SafeArea(',
  '        child: Column(',
  '          children: [',
  '            Align(',
  '              alignment: Alignment.centerRight,',
  "              child: TextButton(onPressed: _finish, child: Text(${c.t('skip')})),",
  '            ),',
  '            Expanded(',
  '              child: PageView.builder(',
  '                controller: _controller,',
  '                itemCount: pages.length,',
  '                onPageChanged: (page) => setState(() => _page = page),',
  '                itemBuilder: (context, index) {',
  '                  final (icon, title, body) = pages[index];',
  '                  return Padding(',
  '                    padding: const EdgeInsets.all(AppSpacings.wLg),',
  '                    child: Column(',
  '                      mainAxisAlignment: MainAxisAlignment.center,',
  '                      children: [',
  '                        Icon(icon, size: 96, color: colors.primary),',
  '                        Gap.hXl,',
  '                        Text(title, style: context.textTheme.headlineSmall, textAlign: TextAlign.center),',
  '                        Gap.hMd,',
  '                        Text(body, style: context.textTheme.bodyLarge, textAlign: TextAlign.center),',
  '                      ],',
  '                    ),',
  '                  );',
  '                },',
  '              ),',
  '            ),',
  '            Row(',
  '              mainAxisAlignment: MainAxisAlignment.center,',
  '              children: [',
  '                for (var i = 0; i < pages.length; i++)',
  '                  AnimatedContainer(',
  '                    duration: const Duration(milliseconds: 200),',
  '                    margin: const EdgeInsets.symmetric(horizontal: AppSpacings.wXxs),',
  '                    width: i == _page ? 24 : 8,',
  '                    height: 8,',
  '                    decoration: BoxDecoration(',
  '                      color: i == _page ? colors.primary : colors.outline,',
  '                      borderRadius: BorderRadius.circular(4),',
  '                    ),',
  '                  ),',
  '              ],',
  '            ),',
  '            Padding(',
  '              padding: const EdgeInsets.all(AppSpacings.wLg),',
  '              child: CustomButton(',
  "                text: isLast ? ${c.t('getStarted')} : ${c.t('next')},",
  '                onPressed: isLast',
  '                    ? _finish',
  '                    : () => _controller.nextPage(',
  '                        duration: const Duration(milliseconds: 300),',
  '                        curve: Curves.easeOut,',
  '                      ),',
  '              ),',
  '            ),',
  '          ],',
  '        ),',
  '      ),',
  '    );',
  '  }',
  '}',
]);

String homeScreenDart(TemplateContext c) {
  final s = c.spec;
  final featureScreen = s.hasFeature ? '${c.entityPlural}Screen' : null;

  return lines([
    "import 'package:flutter/material.dart';",
    if (featureScreen != null) ...c.routerImports,
    ...c.coreImports,
    '',
    if (s.hasAuth) c.pkg('features/auth/application/auth_controller.dart'),
    if (featureScreen != null)
      c.pkg('${c.featureDir}/presentation/${s.table}_screen.dart'),
    ...c.l10nImports,
    '',
    'class HomeScreen extends ConsumerWidget {',
    '  const HomeScreen({super.key});',
    '',
    "  static const String path = '/';",
    '',
    '  @override',
    '  Widget build(BuildContext context, WidgetRef ref) {',
    '    final themeMode = ref.watch(themeProvider);',
    '',
    '    return Scaffold(',
    '      appBar: AppBar(',
    '        title: Text(${dartString(s.displayName)}),',
    if (s.hasAuth) ...[
      '        actions: [',
      '          IconButton(',
      "            tooltip: ${c.t('signOut')},",
      '            icon: const Icon(Icons.logout),',
      '            onPressed: () => ref.read(authControllerProvider).signOut(),',
      '          ),',
      '        ],',
    ],
    '      ),',
    '      body: ListView(',
    '        padding: const EdgeInsets.all(AppSpacings.wLg),',
    '        children: [',
    "          Text(${c.t('homeWelcome')}, style: context.textTheme.headlineMedium),",
    '          Gap.hXs,',
    "          Text(${c.t('homeSubtitle')}, style: context.textTheme.bodyLarge),",
    '          Gap.hXl,',
    "          Text(${c.t('themeLabel')}, style: context.textTheme.titleMedium),",
    '          Gap.hSm,',
    '          SegmentedButton<ThemeMode>(',
    '            segments: [',
    "              ButtonSegment(value: ThemeMode.light, icon: const Icon(Icons.light_mode_outlined), label: Text(${c.t('themeLight')})),",
    "              ButtonSegment(value: ThemeMode.system, icon: const Icon(Icons.brightness_auto_outlined), label: Text(${c.t('themeSystem')})),",
    "              ButtonSegment(value: ThemeMode.dark, icon: const Icon(Icons.dark_mode_outlined), label: Text(${c.t('themeDark')})),",
    '            ],',
    '            selected: {themeMode},',
    '            onSelectionChanged: (selection) =>',
    '                ref.read(themeProvider.notifier).setThemeMode(selection.first),',
    '          ),',
    if (featureScreen != null) ...[
      '          Gap.hXl,',
      '          CustomButton(',
      '            text: ${dartString(c.entityPlural)},',
      '            icon: Icons.list_alt,',
      '            type: ButtonType.outlined,',
      '            onPressed: () => ${c.push(featureScreen)},',
      '          ),',
    ],
    '        ],',
    '      ),',
    '    );',
    '  }',
    '}',
  ]);
}

// ==================== Example feature ====================

String entityDart(TemplateContext c) => lines([
  '/// One row of `${c.spec.table}`. Add fields here, in [fromJson] and [toJson].',
  'class ${c.entity} {',
  '  const ${c.entity}({required this.id, required this.name, this.createdAt});',
  '',
  '  final String id;',
  '  final String name;',
  '  final DateTime? createdAt;',
  '',
  '  factory ${c.entity}.fromJson(Map<String, dynamic> json) => ${c.entity}(',
  "    id: json['id'].toString(),",
  "    name: json['name'] as String? ?? '',",
  "    createdAt: DateTime.tryParse(json['created_at']?.toString() ?? ''),",
  '  );',
  '',
  '  /// The writable fields — `id` and `created_at` come from the backend.',
  "  Map<String, dynamic> toJson() => {'name': name};",
  '}',
]);

String repositoryDart(TemplateContext c) {
  final client = c.spec.dataBackend == Backend.supabase
      ? 'supabaseCrudClientProvider'
      : 'dioCrudClientProvider';
  final e = c.entity;

  return lines([
    "import 'package:riverpod_annotation/riverpod_annotation.dart';",
    ...c.coreImports,
    '',
    c.pkg('${c.featureDir}/domain/${c.spec.feature}.dart'),
    '',
    "part '${c.spec.feature}_repository.g.dart';",
    '',
    '/// Talks to [CrudContract] only, so moving `${c.spec.table}` to another',
    '/// backend means changing the client injected below — nothing else.',
    'class ${e}Repository {',
    '  ${e}Repository(this._client);',
    '',
    '  final CrudContract _client;',
    '',
    "  static const String table = '${c.spec.table}';",
    '',
    '  Future<List<$e>> fetchAll() => _client.query(',
    '    table: table,',
    '    fromJson: $e.fromJson,',
    "    orderBy: 'created_at',",
    '    ascending: false,',
    '  );',
    '',
    '  Future<$e> create(String name) => _client.insert(',
    '    table: table,',
    "    data: $e(id: '', name: name).toJson(),",
    '    fromJson: $e.fromJson,',
    '  );',
    '',
    '  Future<void> delete(String id) => _client.delete(table: table, id: id);',
    '}',
    '',
    '@Riverpod(keepAlive: true)',
    '${e}Repository ${c.entityVar}Repository(Ref ref) =>',
    '    ${e}Repository(ref.watch($client));',
  ]);
}

String listNotifierDart(TemplateContext c) {
  final e = c.entity;
  final p = c.entityPlural;
  final repo = '${c.entityVar}RepositoryProvider';

  return lines([
    "import 'package:riverpod_annotation/riverpod_annotation.dart';",
    '',
    c.pkg('${c.featureDir}/data/${c.spec.feature}_repository.dart'),
    c.pkg('${c.featureDir}/domain/${c.spec.feature}.dart'),
    '',
    "part '${c.spec.table}_notifier.g.dart';",
    '',
    '@riverpod',
    'class $p extends _\$$p {',
    '  @override',
    '  Future<List<$e>> build() => ref.watch($repo).fetchAll();',
    '',
    '  Future<void> add(String name) async {',
    '    final created = await ref.read($repo).create(name);',
    '    state = AsyncData([created, ...state.value ?? const []]);',
    '  }',
    '',
    '  /// Removed from the list first, so a swipe-to-delete leaves the tree at',
    '  /// once; put back if the backend refuses.',
    '  Future<void> remove(String id) async {',
    '    final previous = state.value ?? const <$e>[];',
    '    state = AsyncData([for (final item in previous) if (item.id != id) item]);',
    '    try {',
    '      await ref.read($repo).delete(id);',
    '    } catch (_) {',
    '      state = AsyncData(previous);',
    '      rethrow;',
    '    }',
    '  }',
    '}',
  ]);
}

String listScreenDart(TemplateContext c) {
  final p = c.entityPlural;
  final provider = '${camelCase(c.spec.table)}Provider';

  return lines([
    "import 'package:flutter/material.dart';",
    ...c.coreImports,
    '',
    c.pkg('app/show_error.dart'),
    c.pkg('${c.featureDir}/presentation/${c.spec.table}_notifier.dart'),
    ...c.l10nImports,
    '',
    'class ${p}Screen extends ConsumerWidget {',
    '  const ${p}Screen({super.key});',
    '',
    "  static const String path = '/${c.spec.table.replaceAll('_', '-')}';",
    '',
    '  Future<void> _add(BuildContext context, WidgetRef ref) async {',
    '    final name = await showDialog<String>(',
    '      context: context,',
    '      builder: (_) => const _AddDialog(),',
    '    );',
    '    if (name == null || !context.mounted) return;',
    '    try {',
    '      await ref.read($provider.notifier).add(name);',
    '    } catch (error) {',
    '      if (context.mounted) showError(context, error);',
    '    }',
    '  }',
    '',
    '  Future<void> _remove(BuildContext context, WidgetRef ref, String id) async {',
    '    try {',
    '      await ref.read($provider.notifier).remove(id);',
    '    } catch (error) {',
    '      if (context.mounted) showError(context, error);',
    '    }',
    '  }',
    '',
    '  @override',
    '  Widget build(BuildContext context, WidgetRef ref) {',
    '    final items = ref.watch($provider);',
    '',
    '    return Scaffold(',
    '      appBar: AppBar(title: Text(${dartString(p)})),',
    '      floatingActionButton: FloatingActionButton(',
    "        tooltip: ${c.t('add')},",
    '        onPressed: () => _add(context, ref),',
    '        child: const Icon(Icons.add),',
    '      ),',
    '      body: items.when(',
    '        loading: () => const Center(child: CircularProgressIndicator()),',
    '        error: (error, _) => Center(',
    '          child: Padding(',
    '            padding: const EdgeInsets.all(AppSpacings.wLg),',
    '            child: Column(',
    '              mainAxisSize: MainAxisSize.min,',
    '              children: [',
    '                Text(errorMessage(context, error), textAlign: TextAlign.center),',
    '                Gap.hMd,',
    '                TextButton(',
    '                  onPressed: () => ref.invalidate($provider),',
    "                  child: Text(${c.t('retry')}),",
    '                ),',
    '              ],',
    '            ),',
    '          ),',
    '        ),',
    '        data: (list) => RefreshIndicator(',
    '          onRefresh: () => ref.refresh($provider.future),',
    '          child: list.isEmpty',
    '              ? ListView(',
    '                  children: [',
    '                    Padding(',
    '                      padding: const EdgeInsets.all(AppSpacings.wXl),',
    "                      child: Center(child: Text(${c.t('emptyList')})),",
    '                    ),',
    '                  ],',
    '                )',
    '              : ListView.separated(',
    '                  itemCount: list.length,',
    '                  separatorBuilder: (_, _) => const Divider(height: 1),',
    '                  itemBuilder: (context, index) {',
    '                    final item = list[index];',
    '                    return Dismissible(',
    '                      key: ValueKey(item.id),',
    '                      direction: DismissDirection.endToStart,',
    '                      background: Container(',
    '                        color: context.colorScheme.error,',
    '                        alignment: Alignment.centerRight,',
    '                        padding: const EdgeInsets.symmetric(horizontal: AppSpacings.wLg),',
    '                        child: Icon(Icons.delete_outline, color: context.colorScheme.onError),',
    '                      ),',
    '                      onDismissed: (_) => _remove(context, ref, item.id),',
    '                      child: ListTile(title: Text(item.name)),',
    '                    );',
    '                  },',
    '                ),',
    '        ),',
    '      ),',
    '    );',
    '  }',
    '}',
    '',
    'class _AddDialog extends StatefulWidget {',
    '  const _AddDialog();',
    '',
    '  @override',
    '  State<_AddDialog> createState() => _AddDialogState();',
    '}',
    '',
    'class _AddDialogState extends State<_AddDialog> {',
    '  final _formKey = GlobalKey<FormState>();',
    '  final _name = TextEditingController();',
    '',
    '  @override',
    '  void dispose() {',
    '    _name.dispose();',
    '    super.dispose();',
    '  }',
    '',
    '  void _submit() {',
    '    if (_formKey.currentState!.validate()) {',
    '      Navigator.of(context).pop(_name.text.trim());',
    '    }',
    '  }',
    '',
    '  @override',
    '  Widget build(BuildContext context) {',
    '    return AlertDialog(',
    "      title: Text(${c.t('add')}),",
    '      content: Form(',
    '        key: _formKey,',
    '        child: CustomTextField(',
    '          controller: _name,',
    "          label: ${c.t('nameLabel')},",
    '          textInputAction: TextInputAction.done,',
    '          onSubmitted: (_) => _submit(),',
    "          validator: (value) => Validators.required(value?.trim(), errorMessage: ${c.t('nameRequired')}),",
    '        ),',
    '      ),',
    '      actions: [',
    '        TextButton(',
    '          onPressed: () => Navigator.of(context).pop(),',
    "          child: Text(${c.t('cancel')}),",
    '        ),',
    "        FilledButton(onPressed: _submit, child: Text(${c.t('add')})),",
    '      ],',
    '    );',
    '  }',
    '}',
  ]);
}
